//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_Analytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswersResult
    {
        public int CategoryId { get; set; }
        public int PeriodId { get; set; }
        public Nullable<int> TotalQuestions { get; set; }
        public Nullable<int> TotalUsers { get; set; }
        public Nullable<int> MaxAnswers { get; set; }
        public Nullable<int> Performance { get; set; }
    }
}
