//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_Analytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Answer = new HashSet<Answer>();
            this.Period = new HashSet<Period>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Answer> Answer { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Period> Period { get; set; }
    }
}
