INSERT INTO [NS].[Role] ([Name]) VALUES ('Admin')
INSERT INTO [NS].[Role] ([Name]) VALUES ('Manager')
INSERT INTO [NS].[Role] ([Name]) VALUES ('Analist')

INSERT INTO [NS].[User] Values ('Admin@admin.nl', 1, 'AIu81EER2TVIw/UJ+N0+QT3FgjTd7QtPyjI8nVGUB6C8rkrRX9KESuZhzV2m3vb3ww==', '', NULL, 0, 0, NULL, 1, 0, 'Admin@admin.nl')

INSERT INTO [NS].[UserRole] Values (1, 1)

INSERT INTO [dbo].[Category] ([Name]) VALUES ('QuickScan - Elicitatie')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('QuickScan - Analyse')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('QuickScan - Specificatie')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('QuickScan - Validatie')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('MaturityScan - REMS1')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('MaturityScan - REMS2')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('MaturityScan - REMS3')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('MaturityScan - REMS4')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('MaturityScan - REMS5')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('MaturityScan - REMS6')

INSERT INTO Project VALUES ('-- Geen --')

INSERT INTO Period VALUES ('-- Geen --', 0, 1)


INSERT INTO QUESTION VALUES ('Zijn er verschillende groepen?', 1)
INSERT INTO QUESTION VALUES ('Zijn de stakeholders bekend?', 1)
INSERT INTO QUESTION VALUES ('Wie is de vertegenwoordiger van de groep?', 1)
INSERT INTO QUESTION VALUES ('Is het domein duidelijk voor de requirements?', 1)
INSERT INTO QUESTION VALUES ('Ondersteunt het systeem het bedrijfsproces?', 1)
INSERT INTO QUESTION VALUES ('Is de noodzakelijke voorwaarde van de requirements juist?', 1)
INSERT INTO QUESTION VALUES ('Is de noodzakelijke voorwaarde van de requirements volledig?', 1)
INSERT INTO QUESTION VALUES ('Is er genoeg capaciteit uit de operationele processen?', 1)
INSERT INTO QUESTION VALUES ('Biedt het systeem ondersteuning aan het bedrijfsproces?', 1)
INSERT INTO QUESTION VALUES ('Zijn de requirements geaccepteerd door de gebruikers?', 1)
INSERT INTO QUESTION VALUES ('Zijn de gebruikers betrokken geweest bij het project?', 1)
INSERT INTO QUESTION VALUES ('Zijn de wensen geïnventariseerd?', 1)
INSERT INTO QUESTION VALUES ('Zijn de eisen geïnventariseerd?', 1)
INSERT INTO QUESTION VALUES ('Zijn de requirements expliciet gemaakt?', 1)
INSERT INTO QUESTION VALUES ('Is de informatie analist actief betrokken geweest tijdens het proces?', 1)
INSERT INTO QUESTION VALUES ('Zijn de requirements vastgelegd in een brondocument?', 1)
INSERT INTO QUESTION VALUES ('Zijn de gedetaileerde requirements herleid van de oorspronkelijke requirements?', 1)

INSERT INTO QUESTION VALUES ('Is de essentie van een specifieke requirement vastgesteld?', 2)
INSERT INTO QUESTION VALUES ('Is de formulering van de requirements geanalyseerd en geconfirmeerd met de stakeholder?', 2)
INSERT INTO QUESTION VALUES ('Heeft de informatie analist overlegd met de stakeholder, wat de essentie is van elk requirement?', 2)
INSERT INTO QUESTION VALUES ('Is het hogere doel van een requirement vastgesteld? ', 2)
INSERT INTO QUESTION VALUES ('Zijn de requirements relevant?', 2)
INSERT INTO QUESTION VALUES ('Zijn de business requirements vastgelegd?', 2)
INSERT INTO QUESTION VALUES ('Is het vervullen van een requirement de enige zinvolle manier om het hogere requirement in te vullen?', 2)

INSERT INTO QUESTION VALUES ('Zijn de resultaten van de analyse stap vastgelegd?', 3)
INSERT INTO QUESTION VALUES ('Is er een eenduidige formulering gebruikt?', 3)
INSERT INTO QUESTION VALUES ('Zijn de use cases gemaakt?', 3)
INSERT INTO QUESTION VALUES ('Is een datamodel gemaakt?', 3)
INSERT INTO QUESTION VALUES ('Zijn de modellen gevalideerd?', 3)
INSERT INTO QUESTION VALUES ('Zijn er wijzigingen?', 3)
INSERT INTO QUESTION VALUES ('Is het document goedgekeurd door de stakeholder?', 3)

INSERT INTO QUESTION VALUES ('Zijn de requirements verwoord naar de behoeften van de gebruiker?', 4)
INSERT INTO QUESTION VALUES ('Zijn de resultaten van de specificatie gecontroleerd?', 4)
INSERT INTO QUESTION VALUES ('Zijn de desbetreffende requirements door de stakeholders beoordeeld?', 4)
INSERT INTO QUESTION VALUES ('Zijn de juiste requirements beschreven?', 4)
INSERT INTO QUESTION VALUES ('Zijn de requirements volledig?', 4)
INSERT INTO QUESTION VALUES ('Zijn de requirements consistent?', 4)

-- REMS 1 --
INSERT INTO QUESTION VALUES ('Is de probleem formulering beschreven?', 5)
INSERT INTO QUESTION VALUES ('Is het probleem begrijpelijk?', 5)
INSERT INTO QUESTION VALUES ('Begrijpt het team het probleem?', 5)
INSERT INTO QUESTION VALUES ('Zijn de stakeholders (incl. management) het eens met de probleem formulering?', 5)
INSERT INTO QUESTION VALUES ('Is het duidelijk voor het team welk probleem ze gaan oplossen?', 5)
INSERT INTO QUESTION VALUES ('Is de doelstelling gedocumenteerd?', 5)
INSERT INTO QUESTION VALUES ('Is de doelstelling gedocumenteerd in de NS business case?', 5)
INSERT INTO QUESTION VALUES ('Zijn de werkzaamheden beschreven?', 5)
INSERT INTO QUESTION VALUES ('Is het bedrijfsbelang bekend?', 5)
INSERT INTO QUESTION VALUES ('Zijn de doelstellingen beschreven in meetbare eenheden?', 5)
INSERT INTO QUESTION VALUES ('Is er een analyse gedaan naar de grondoorzaak?', 5)
INSERT INTO QUESTION VALUES ('Zijn de teamleden ervan bewust dat er een “echt probleem” wordt opgelost, en niet een symptoom of algemeen basisprobleem?', 5)
INSERT INTO QUESTION VALUES ('Is de grens van de oplossing geïdentificeerd?', 5)
INSERT INTO QUESTION VALUES ('Zijn de overige interacties met het systeem geïdentificeerd?', 5)
INSERT INTO QUESTION VALUES ('Is het systeem onderverdeeld in subsystemen?', 5)
INSERT INTO QUESTION VALUES ('Zo ja, zijn alle subsystemen gedefinieerd?', 5)
INSERT INTO QUESTION VALUES ('Zijn de grenzen van elk subsysteem begrepen?', 5)
INSERT INTO QUESTION VALUES ('Is er een plan voor het identificeren en tot het komen van requirements?', 5)
INSERT INTO QUESTION VALUES ('Zijn alle gebruikers van het systeem geïdentificeerd?', 5)
INSERT INTO QUESTION VALUES ('Zijn alle stakeholders geïdentificeerd?', 5)
INSERT INTO QUESTION VALUES ('Is er een gedegen stakeholderanalyse geweest?', 5)
INSERT INTO QUESTION VALUES ('Heb je buiten de set van de huidige gebruikers en stakeholders gekeken, bijvoorbeeld de personen die te maken hebben met de administratie, installatie, support of training?', 5)
INSERT INTO QUESTION VALUES ('Weten de teamleden dat alle stakeholders zijn geïdentificeerd?', 5)
INSERT INTO QUESTION VALUES ('Heeft het team alle beperkingen van het systeem beschreven?', 5)
INSERT INTO QUESTION VALUES ('Heeft het team de ontwikkel beperkingen geïdentificeerd?', 5)
INSERT INTO QUESTION VALUES ('Zijn de beperkte bronnen (zoals budget, productie kosten, politiek of contractuele requirements, systeem requirements, omgeving factoren, regulaties, personeel, software proces en tooling) in aanmerking gebracht?', 5)
INSERT INTO QUESTION VALUES ('Heb je alle actoren gevonden die interactie hebben met het systeem?', 5)
INSERT INTO QUESTION VALUES ('Is elke actor betrokken bij tenminste één use case?', 5)
INSERT INTO QUESTION VALUES ('Zijn er actoren die een vergelijkbare rol hebben in relatie met het systeem? Zo ja, probeer het onder één actor te brengen.', 5)
INSERT INTO QUESTION VALUES ('Is er een actor die het systeem op meerdere manieren gebruikt? Zo ja, dan moet je verschillende actoren beschrijven.', 5)
INSERT INTO QUESTION VALUES ('Hebben de actoren intuïtieve en beschrijfbare namen? Kunnen gebruikers en klanten de namen begrijpen?', 5)
INSERT INTO QUESTION VALUES ('Zijn de functionaliteiten van de business use case begrijpelijk van het voorgestelde systeem?', 5)
INSERT INTO QUESTION VALUES ('Is het business object model begrijpelijk voor de entiteiten in het betrokken business proces?', 5)
INSERT INTO QUESTION VALUES ('Heeft het team begrepen wat de specifieke functionaliteiten zijn van het voorgestelde systeem?', 5)

INSERT INTO QUESTION VALUES ('Is er een gestructureerd interview afgenomen?', 6)
INSERT INTO QUESTION VALUES ('Heeft het interview alle belangrijke aspecten van het systeem behandeld? (Denk aan: product requirements, het doel, het gebruik, betrouwbaarheid, in gebruik neming, beheer)', 6)
INSERT INTO QUESTION VALUES ('Was het aantal geïnterviewde gebruikers en stakeholders voldoende?', 6)
INSERT INTO QUESTION VALUES ('Zijn de interviews vrij van tegenstrijdigheid om de kwaliteit te kunnen waarborgen?', 6)
INSERT INTO QUESTION VALUES ('Zijn de andere hoofd-invloeden begrepen door het team?', 6)
INSERT INTO QUESTION VALUES ('Begrijp je wie de gebruikers zijn en wat de geschiktheid moet zijn om de applicatie te gebruiken?', 6)
INSERT INTO QUESTION VALUES ('Heb jij de hoofdgebruiker ontdekt die nodig is om gericht het product te ontwikkelen?', 6)
INSERT INTO QUESTION VALUES ('Zijn de hoogste prioriteiten geconvergeerd na de redelijke interviews?', 6)
INSERT INTO QUESTION VALUES ('Zijn de gegevens over gebruikers, behoeften, en andere gesuggereerde features samengevat voor toekomstige referentie?', 6)
INSERT INTO QUESTION VALUES ('Is er een workshop georganiseerd met de vereiste stakeholders?', 6)
INSERT INTO QUESTION VALUES ('Was de workshop zo georganiseerd dat de stakeholders werden aangemoedigd om input te geven?', 6)
INSERT INTO QUESTION VALUES ('Resulteerde de workshop tot een eenduidig begrip van het toekomstige systeem?', 6)
INSERT INTO QUESTION VALUES ('Was het development team betrokken om redelijke technische-en projectmatige haalbaarheid te verzekeren?', 6)
INSERT INTO QUESTION VALUES ('Is er een brainstormsessie gehouden voor het verzamelen van requirements?', 6)
INSERT INTO QUESTION VALUES ('Worden de ideeën en resultaten van de brainstormsessie gedocumenteerd? ', 6)
INSERT INTO QUESTION VALUES ('Bestaat er een prioriteiten lijst van features?', 6)
INSERT INTO QUESTION VALUES ('Is er een ruwe schatting gemaakt van de inspanning van het development team?', 6)
INSERT INTO QUESTION VALUES ('Is de opgenomen informatie gedocumenteerd voor verdere referentie?', 6)
INSERT INTO QUESTION VALUES ('Als de applicatie innovatief is, heb jij middelen ontwikkeld om de applicatie te demonstreren aan de gebruiker?', 6)
INSERT INTO QUESTION VALUES ('Was de reactie van de gebruikers in acht genomen, en gereflecteerd op het huidige begrip van het systeem? ', 6)
INSERT INTO QUESTION VALUES ('Kun je een paar voorbeeld use cases beschrijven over “hoe het systeem gebruikt zal worden”?', 6)


INSERT INTO QUESTION VALUES ('Heb je het plan opgericht voor de requirements van de organisatie?', 7)
INSERT INTO QUESTION VALUES ('Heb je begrepen welke tool je gebruikt voor het beheren van het proces?', 7)
INSERT INTO QUESTION VALUES ('Heeft je organisatie systeem alle typen requirements opgenomen?', 7)
INSERT INTO QUESTION VALUES ('Ben je nog op zoek naar design beperkingen?', 7)
INSERT INTO QUESTION VALUES ('Heb je een vision document voor het project?', 7)
INSERT INTO QUESTION VALUES ('Heeft het vision document relevante bronnen (auteur, stakeholders, experts, development team) over de aspecten van het project (systeem requirements, beperkingen, andere systemen en applicaties, concurrerende producten)?', 7)
INSERT INTO QUESTION VALUES ('Is het vision document beschreven in een gevestigd template voor bepaalde doeleinden?', 7)
INSERT INTO QUESTION VALUES ('Heb je de basis use cases geïdentificeerd (benoemd en beschreven)?', 7)
INSERT INTO QUESTION VALUES ('Is er een product manager of project verdediger die het team ondersteunt?', 7)
INSERT INTO QUESTION VALUES ('Is hij/zij de officiële persoon van feature-level veranderingen?', 7)
INSERT INTO QUESTION VALUES ('Weet je hoe je het product beschrijft aan de buitenwereld?', 7)
INSERT INTO QUESTION VALUES ('Heb je de requirements/het beleid gedefinieerd en beschreven voor documentatie? (denk aan: installatie, prijs, configuratie, beheer, licentie, training voor eindgebruiker, product benaming, merk, label)', 7)


INSERT INTO QUESTION VALUES ('Heb je de risico’s voor de features ingeschat en geprioriteerd?', 8)
INSERT INTO QUESTION VALUES ('Heb je de baseline requirements vastgesteld voor de release waar je aan werkt?', 8)
INSERT INTO QUESTION VALUES ('Begrijp je welke features kritisch zijn voor de release?', 8)
INSERT INTO QUESTION VALUES ('Heeft het project een haalbare afbakening?', 8)
INSERT INTO QUESTION VALUES ('Heb jij de mogelijke -en niet mogelijke beslissingen genomen voor het project voor de afbakening van het project?', 8)
INSERT INTO QUESTION VALUES ('Zijn de hoofdmanagers en stakeholders het eens met de afbakening?', 8)
INSERT INTO QUESTION VALUES ('Zijn de verwachtingen voor de huidige release door het team begrepen?', 8)
INSERT INTO QUESTION VALUES ('Zijn de verwachtingen besproken en is er een akkoord gekomen met de stakeholders buiten het team (inclusief de eindgebruiker/klant)?', 8)


INSERT INTO QUESTION VALUES ('Zijn de use cases gemaakt volgens de theorie van use case 2.0?', 9)
INSERT INTO QUESTION VALUES ('Als het systeem subsystemen heeft, reflecteert het use case model juist op de subsystemen?', 9)
INSERT INTO QUESTION VALUES ('Heb je voor alle use case modellen een reflectie gedaan?', 9)
INSERT INTO QUESTION VALUES ('Zijn de use case modellen uniek en intuïtief?', 9)
INSERT INTO QUESTION VALUES ('Heeft de use case modellen begrijpbare namen, zodat er in een later stadium geen verwarring komt?', 9)
INSERT INTO QUESTION VALUES ('Zijn alle nodige systeem features geïdentificeerd in één of meer use cases?', 9)
INSERT INTO QUESTION VALUES ('Begrijpen klanten en gebruikers de namen en beschrijvingen van de use cases?', 9)
INSERT INTO QUESTION VALUES ('Als je kijkt naar het use case model, kun je een goed beeld vormen van de systeem functionaliteiten en hoe ze zijn gerelateerd?', 9)
INSERT INTO QUESTION VALUES ('Komen de uitgewerkte use cases overeen met alle functionele requirements?', 9)
INSERT INTO QUESTION VALUES ('Heeft het use case model overbodigheden?', 9)
INSERT INTO QUESTION VALUES ('Heeft het use case model meer functionaliteiten dan er staat beschreven in de requirements?', 9)
INSERT INTO QUESTION VALUES ('Heeft het model geïdentificeerde externe relaties?', 9)
INSERT INTO QUESTION VALUES ('Kan het model worden versimpeld met alternatieve relaties?', 9)
INSERT INTO QUESTION VALUES ('Is elke use case betrokken bij tenminste één actor?', 9)
INSERT INTO QUESTION VALUES ('Geeft de beschrijving een goed beeld over de use case?', 9)
INSERT INTO QUESTION VALUES ('Is het duidelijk wie de use case zal uitvoeren? Is het doel van de use case vastgesteld?', 9)
INSERT INTO QUESTION VALUES ('Hebben de uitgebreide use cases de nodige secties en geschikte inhoud voor namen, actoren, korte beschrijving, primaire en alternatieve event flows, pre- en post condities, en speciale requirements?', 9)
INSERT INTO QUESTION VALUES ('Hebben de uitgebreide use cases de nodige secties en geschikte inhoud voor namen, actoren, korte beschrijving, primaire en alternatieve event flows, pre- en post condities, en speciale requirements?', 9)
INSERT INTO QUESTION VALUES ('Is het duidelijk hoe en wanneer de use case event flows starten en eindigen?', 9)
INSERT INTO QUESTION VALUES ('Is elke use case onafhankelijk van elkaar?', 9)
INSERT INTO QUESTION VALUES ('Zijn er use cases die vergelijkbare gedragingen/flows hebben?', 9)
INSERT INTO QUESTION VALUES ('Is een deel van de use case event flows al gemodelleerd in een andere use case?', 9)
INSERT INTO QUESTION VALUES ('Moeten de event flows van één use case in een andere event flow worden geplaatst?', 9)
INSERT INTO QUESTION VALUES ('Voldoen de use cases aan de requirements voor de besturing? Zijn de use case specificaties gerefereerd aan de non-functionele requirements waar het nodig is?', 9)
INSERT INTO QUESTION VALUES ('Is de frequentie van communiceren tussen de actor en de use case in overeenstemming met de gebruikersverwachting?', 9)
INSERT INTO QUESTION VALUES ('Is er een beschrijving van wat er gebeurt als een conditie niet is voldaan?', 9)
INSERT INTO QUESTION VALUES ('Zijn er use cases die te complex zijn?', 9)
INSERT INTO QUESTION VALUES ('Is de interactie tussen de actor en informatie uitwisseling duidelijk?', 9)
INSERT INTO QUESTION VALUES ('Heb je een geschikt template gebruikt voor de specifieke doelen?', 9)
INSERT INTO QUESTION VALUES ('Zijn de functionele requirements, inclusief het use case model, gereflecteerd in de aanvullende specificaties?', 9)
INSERT INTO QUESTION VALUES ('Zijn de non-functionele requirements (zoals bruikbaarheid, betrouwbaarheid, performance, en beheerbaarheid) geïdentificeerd en beschreven?', 9)
INSERT INTO QUESTION VALUES ('Zijn de passende ontwerp beperkingen geïdentificeerd en beschreven?', 9)
INSERT INTO QUESTION VALUES ('Zijn aanvullende requirements gelinkt aan de use cases (waar nodig is)?', 9)
INSERT INTO QUESTION VALUES ('Over het algemeen, heeft het team het juiste niveau van de specificaties voor het project bereikt?', 9)
INSERT INTO QUESTION VALUES ('Hoe weet je dat het juiste niveau is bereikt?', 9)
INSERT INTO QUESTION VALUES ('Zijn er voldoende technische methodes gebruikt om de dubbelzinnigheid te verwijderen? (Vooral in gevallen waar er geen miscommunicatie kan plaatsvinden)', 9)
INSERT INTO QUESTION VALUES ('Als er voldoende technische methodes zijn, zijn deze methodes begrepen door de stakeholders?', 9)


INSERT INTO QUESTION VALUES ('Is er een use case realisatie (samenwerking) voor alle use cases in het use case model?', 10)
INSERT INTO QUESTION VALUES ('Zijn er andere realisaties voor andere functionele requirements?', 10)
INSERT INTO QUESTION VALUES ('Heb je de use cases gebruikt voor de test case ontwikkeling?', 10)
INSERT INTO QUESTION VALUES ('Heb je de NS processen gebruikt om te testen?', 10)
INSERT INTO QUESTION VALUES ('Zijn er één of meerdere test gevallen voor elke use case?', 10)
INSERT INTO QUESTION VALUES ('Heb jij een plan gemaakt voor de requirements traceerbaarheid?', 10)
INSERT INTO QUESTION VALUES ('Heb je voldoende tooling geïdentificeerd en geïmplementeerd?', 10)
INSERT INTO QUESTION VALUES ('Heb jij een specifiek traceerbaar model geïdentificeerd en gevolgd voor dit project?', 10)
INSERT INTO QUESTION VALUES ('Heb je de traceerbaarheid zoveel mogelijk benut?', 10)
INSERT INTO QUESTION VALUES ('Begrijp je de bron veranderingen en dynamische veranderingen van het project?', 10)
INSERT INTO QUESTION VALUES ('Heeft de project/product manager de controle over dit project?', 10)
INSERT INTO QUESTION VALUES ('Is er een passende change control board opgericht en is dat functioneel voor het project?', 10)
INSERT INTO QUESTION VALUES ('Kun je veranderingen vastleggen en effectief beheren met de geïmplementeerde tooling?', 10)
INSERT INTO QUESTION VALUES ('Heb je een manier om defecten van het project vast te leggen en traceren?', 10)
INSERT INTO QUESTION VALUES ('Heb je de juiste requirements methode gebruikt?', 10)
INSERT INTO QUESTION VALUES ('Reflecteert het de hoofd prioriteiten van kritische aspecten en veiligheid van het project?', 10)
INSERT INTO QUESTION VALUES ('Verwijdert de methode de onnodige documentatie?', 10)
INSERT INTO QUESTION VALUES ('Ondersteunt de tooling de gekozen methode voldoende?', 10)
