INSERT INTO [NS].[Role] ([Name]) VALUES ('Geen')
INSERT INTO [NS].[Role] ([Name]) VALUES ('Admin')
INSERT INTO [NS].[Role] ([Name]) VALUES ('Business Analist')
INSERT INTO [NS].[Role] ([Name]) VALUES ('Manager')

INSERT INTO [NS].[User] Values ('Admin@admin.nl', 1, 'AIu81EER2TVIw/UJ+N0+QT3FgjTd7QtPyjI8nVGUB6C8rkrRX9KESuZhzV2m3vb3ww==', '', NULL, 0, 0, NULL, 1, 0, 'Admin@admin.nl')

INSERT INTO [NS].[UserRole] Values (1, 1)

INSERT INTO [dbo].[Category] ([Name]) VALUES ('QuickScan - Elicitatie')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('QuickScan - Analyse')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('QuickScan - Specificatie')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('QuickScan - Validatie')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('MaturityScan - REMS1')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('MaturityScan - REMS2')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('MaturityScan - REMS3')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('MaturityScan - REMS4')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('MaturityScan - REMS5')
INSERT INTO [dbo].[Category] ([Name]) VALUES ('MaturityScan - REMS6')

INSERT INTO Project VALUES ('-- Geen --')

INSERT INTO Period VALUES ('-- Geen --', 0, 1)


INSERT INTO QUESTION VALUES ('Zijn er verschillende groepen?', 1)
INSERT INTO QUESTION VALUES ('Zijn de stakeholders bekend?', 1)
INSERT INTO QUESTION VALUES ('Wie is de vertegenwoordiger van de groep?', 1)
INSERT INTO QUESTION VALUES ('Is het domein duidelijk voor de requirements?', 1)
INSERT INTO QUESTION VALUES ('Ondersteunt het systeem het bedrijfsproces?', 1)
INSERT INTO QUESTION VALUES ('Is de noodzakelijke voorwaarde van de requirements juist?', 1)
INSERT INTO QUESTION VALUES ('Is de noodzakelijke voorwaarde van de requirements volledig?', 1)
INSERT INTO QUESTION VALUES ('Is er genoeg capaciteit uit de operationele processen?', 1)
INSERT INTO QUESTION VALUES ('Biedt het systeem ondersteuning aan het bedrijfsproces?', 1)
INSERT INTO QUESTION VALUES ('Zijn de requirements geaccepteerd door de gebruikers?', 1)
INSERT INTO QUESTION VALUES ('Zijn de gebruikers betrokken geweest bij het project?', 1)
INSERT INTO QUESTION VALUES ('Zijn de wensen geïnventariseerd?', 1)
INSERT INTO QUESTION VALUES ('Zijn de eisen geïnventariseerd?', 1)
INSERT INTO QUESTION VALUES ('Zijn de requirements expliciet gemaakt?', 1)
INSERT INTO QUESTION VALUES ('Is de informatie analist actief betrokken geweest tijdens het proces?', 1)
INSERT INTO QUESTION VALUES ('Zijn de requirements vastgelegd in een brondocument?', 1)
INSERT INTO QUESTION VALUES ('Zijn de gedetaileerde requirements herleid van de oorspronkelijke requirements?', 1)

INSERT INTO QUESTION VALUES ('Is de essentie van een specifieke requirement vastgesteld?', 2)
INSERT INTO QUESTION VALUES ('Is de formulering van de requirements geanalyseerd en geconfirmeerd met de stakeholder?', 2)
INSERT INTO QUESTION VALUES ('Heeft de informatie analist overlegd met de stakeholder, wat de essentie is van elk requirement?', 2)
INSERT INTO QUESTION VALUES ('Is het hogere doel van een requirement vastgesteld? ', 2)
INSERT INTO QUESTION VALUES ('Zijn de requirements relevant?', 2)
INSERT INTO QUESTION VALUES ('Zijn de business requirements vastgelegd?', 2)
INSERT INTO QUESTION VALUES ('Is het vervullen van een requirement de enige zinvolle manier om het hogere requirement in te vullen?', 2)

INSERT INTO QUESTION VALUES ('Zijn de resultaten van de analyse stap vastgelegd?', 3)
INSERT INTO QUESTION VALUES ('Is er een eenduidige formulering gebruikt?', 3)
INSERT INTO QUESTION VALUES ('Zijn de use cases gemaakt?', 3)
INSERT INTO QUESTION VALUES ('Is een datamodel gemaakt?', 3)
INSERT INTO QUESTION VALUES ('Zijn de modellen gevalideerd?', 3)
INSERT INTO QUESTION VALUES ('Zijn er wijzigingen?', 3)
INSERT INTO QUESTION VALUES ('Is het document goedgekeurd door de stakeholder?', 3)

INSERT INTO QUESTION VALUES ('Zijn de requirements verwoord naar de behoeften van de gebruiker?', 4)
INSERT INTO QUESTION VALUES ('Zijn de resultaten van de specificatie gecontroleerd?', 4)
INSERT INTO QUESTION VALUES ('Zijn de desbetreffende requirements door de stakeholders beoordeeld?', 4)
INSERT INTO QUESTION VALUES ('Zijn de juiste requirements beschreven?', 4)
INSERT INTO QUESTION VALUES ('Zijn de requirements volledig?', 4)
INSERT INTO QUESTION VALUES ('Zijn de requirements consistent?', 4)

-- REMS 1 --
INSERT INTO QUESTION VALUES ('Is de probleem formulering beschreven?', 5)
INSERT INTO QUESTION VALUES ('Is het probleem begrijpelijk?', 5)
INSERT INTO QUESTION VALUES ('Begrijpt het team het probleem?', 5)
INSERT INTO QUESTION VALUES ('Zijn de stakeholders (incl. management) het eens met de probleem formulering?', 5)
INSERT INTO QUESTION VALUES ('Is het duidelijk voor het team welk probleem ze gaan oplossen?', 5)
INSERT INTO QUESTION VALUES ('Is de doelstelling gedocumenteerd?', 5)
INSERT INTO QUESTION VALUES ('Is de doelstelling gedocumenteerd in de NS business case?', 5)
INSERT INTO QUESTION VALUES ('Zijn de werkzaamheden beschreven?', 5)
INSERT INTO QUESTION VALUES ('Is het bedrijfsbelang bekend?', 5)
INSERT INTO QUESTION VALUES ('Zijn de doelstellingen beschreven in meetbare eenheden?', 5)
INSERT INTO QUESTION VALUES ('Is er een analyse gedaan naar de grondoorzaak?', 5)
INSERT INTO QUESTION VALUES ('Zijn de teamleden ervan bewust dat er een “echt probleem” wordt opgelost, en niet een symptoom of algemeen basisprobleem?', 5)
INSERT INTO QUESTION VALUES ('Is de grens van de oplossing geïdentificeerd?', 5)
INSERT INTO QUESTION VALUES ('Zijn de overige interacties met het systeem geïdentificeerd?', 5)
INSERT INTO QUESTION VALUES ('Is het systeem onderverdeeld in subsystemen?', 5)
INSERT INTO QUESTION VALUES ('Zo ja, zijn alle subsystemen gedefinieerd?', 5)
INSERT INTO QUESTION VALUES ('Zijn de grenzen van elk subsysteem begrepen?', 5)
INSERT INTO QUESTION VALUES ('Is er een plan voor het identificeren en tot het komen van requirements?', 5)
INSERT INTO QUESTION VALUES ('Zijn alle gebruikers van het systeem geïdentificeerd?', 5)
INSERT INTO QUESTION VALUES ('Zijn alle stakeholders geïdentificeerd?', 5)
INSERT INTO QUESTION VALUES ('Is er een gedegen stakeholderanalyse geweest?', 5)
INSERT INTO QUESTION VALUES ('Heb je buiten de set van de huidige gebruikers en stakeholders gekeken, bijvoorbeeld de personen die te maken hebben met de administratie, installatie, support of training?', 5)
INSERT INTO QUESTION VALUES ('Weten de teamleden dat alle stakeholders zijn geïdentificeerd?', 5)
INSERT INTO QUESTION VALUES ('Heeft het team alle beperkingen van het systeem beschreven?', 5)
INSERT INTO QUESTION VALUES ('Heeft het team de ontwikkel beperkingen geïdentificeerd?', 5)
INSERT INTO QUESTION VALUES ('Zijn de beperkte bronnen (zoals budget, productie kosten, politiek of contractuele requirements, systeem requirements, omgeving factoren, regulaties, personeel, software proces en tooling) in aanmerking gebracht?', 5)
INSERT INTO QUESTION VALUES ('Heb je alle actoren gevonden die interactie hebben met het systeem?', 5)
INSERT INTO QUESTION VALUES ('Is elke actor betrokken bij tenminste één use case?', 5)
INSERT INTO QUESTION VALUES ('Zijn er actoren die een vergelijkbare rol hebben in relatie met het systeem? Zo ja, probeer het onder één actor te brengen.', 5)
INSERT INTO QUESTION VALUES ('Is er een actor die het systeem op meerdere manieren gebruikt? Zo ja, dan moet je verschillende actoren beschrijven.', 5)
INSERT INTO QUESTION VALUES ('Hebben de actoren intuïtieve en beschrijfbare namen? Kunnen gebruikers en klanten de namen begrijpen?', 5)
INSERT INTO QUESTION VALUES ('Zijn de functionaliteiten van de business use case begrijpelijk van het voorgestelde systeem?', 5)
INSERT INTO QUESTION VALUES ('Is het business object model begrijpelijk voor de entiteiten in het betrokken business proces?', 5)
INSERT INTO QUESTION VALUES ('Heeft het team begrepen wat de specifieke functionaliteiten zijn van het voorgestelde systeem?', 5)